kind: Namespace
apiVersion: v1
metadata:
  name: clients
  labels:
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: applications
  labels:
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    istio-injection: disabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: opentelemetry-collector
  labels:
    istio-injection: disabled        