# Source: k8s-monitoring/charts/alloy-events/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-k8s-monitoring-alloy-events
  labels:
    helm.sh/chart: alloy-events-0.9.1
    app.kubernetes.io/name: alloy-events
    app.kubernetes.io/instance: grafana-k8s-monitoring
    
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-k8s-monitoring-alloy-events
subjects:
  - kind: ServiceAccount
    name: grafana-k8s-monitoring-alloy-events
    namespace: monitoring
---