apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy-traces
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy-logs
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-alloy-metrics
  namespace: monitoring  