apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-alloy-logs
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-alloy-logs
  serviceName: grafana-alloy-logs
  template:
    metadata:
      labels:
        name: grafana-alloy-logs
    spec:
      containers:
      - args:
          - run
          - /etc/agent/config.alloy
          - --storage.path=/var/lib/alloy/data
          - --server.http.listen-addr=0.0.0.0:12345      
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana/alloy:v1.3.0
        imagePullPolicy: IfNotPresent
        name: grafana-alloy-traces
        ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 9464        
        volumeMounts:
        - mountPath: /etc/agent/config.alloy
          name: grafana-alloy-logs
      serviceAccountName: grafana-alloy-logs
      volumes:
      - configMap:
          name: grafana-alloy-logs
        name: grafana-alloy-logs
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: agent-wal-logs
      namespace: monitoring
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-alloy-logs-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}