 apiVersion: opentelemetry.io/v1alpha1
 kind: OpenTelemetryCollector
 metadata:
   labels:
     app: opentelemetry
     component: collector
   name: otel-collector
   namespace: opentelemetry-collector
 spec:
   mode: sidecar
   config: |
     receivers:
       otlp:
         protocols:
           grpc:
             endpoint: 0.0.0.0:4317
     exporters:
       debug:
       otlp:
         endpoint: http://lb-grafana-alloy.monitoring.svc.cluster.local:4317
         tls:
           insecure: true
     service:
       pipelines:
         traces:
           receivers: [otlp]
           exporters: [otlp]



