# Source: k8s-monitoring/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "analyze-grafana-k8s-monitoring"
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "grafana-k8s-monitoring"
    app.kubernetes.io/version: 2.8.3
    helm.sh/chart: "k8s-monitoring-1.6.0"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  restartPolicy: OnFailure
  nodeSelector:
        kubernetes.io/os: linux
  containers:
    - name: config-analysis
      image: ghcr.io/grafana/k8s-monitoring-test:1.6.0
      command: [/etc/bin/config-analysis.sh]
      env:
        - name: ALLOY_HOST
          value: grafana-k8s-monitoring-alloy.monitoring.svc:12345