apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-traces
  namespace: monitoring
data:
  config.alloy: |
    // OtelCol configs
    logging {
        level  = "debug"
        format = "json"
    }

    otelcol.auth.basic "tempo" {
      username = 406010
      password = "eyJrIjoiNGRjNDU3MmQ1MTVlOTk2ODQ1Zjk1MGNmZDcwNGQyMmIwOGEwNjA3MyIsIm4iOiJyb2dtZW4tcHVibGlzaGVyIiwiaWQiOjgxNDMyMn0="
    }
    otelcol.auth.basic "promp" {
      username = 406010
      password ="eyJrIjoiNGRjNDU3MmQ1MTVlOTk2ODQ1Zjk1MGNmZDcwNGQyMmIwOGEwNjA3MyIsIm4iOiJyb2dtZW4tcHVibGlzaGVyIiwiaWQiOjgxNDMyMn0="
    }
    otelcol.auth.basic "otlphttp" {
      username = 560101
      password ="eyJrIjoiNGRjNDU3MmQ1MTVlOTk2ODQ1Zjk1MGNmZDcwNGQyMmIwOGEwNjA3MyIsIm4iOiJyb2dtZW4tcHVibGlzaGVyIiwiaWQiOjgxNDMyMn0="
    }

    otelcol.receiver.otlp "receiverbase" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }      
      output {
        metrics = [otelcol.processor.resourcedetection.default.input]
        traces  = [otelcol.processor.resourcedetection.default.input]
      }
    }

    // Resource Detection Processor
    otelcol.processor.resourcedetection "default" {
      detectors = ["env","system"]
      system {
        hostname_sources = ["os"]
      }
      output {
        metrics = [otelcol.processor.k8sattributes.default.input]
        traces = [otelcol.processor.k8sattributes.default.input]
      }
    }

    // K8s Attributes Processor
    otelcol.processor.k8sattributes "default" {
      extract {
        metadata = ["k8s.namespace.name","k8s.pod.name","k8s.deployment.name","k8s.replicaset.name","k8s.statefulset.name","k8s.daemonset.name","k8s.cronjob.name","k8s.job.name","k8s.node.name","k8s.pod.uid","k8s.pod.start_time"]
      }
      pod_association {
        source {
          from = "resource_attribute"
          name = "k8s.pod.ip"
        }
        source {
          from = "resource_attribute"
          name = "k8s.pod.uid"
        }
        source {
          from = "connection"
        }
      }
  
      output {
        //metrics = [otelcol.processor.filter.filter_app_metrics.input]
        metrics = [otelcol.processor.transform.default.input] 
        traces  = [otelcol.processor.memory_limiter.memory_limiter.input]
      }
    }


    otelcol.processor.memory_limiter "memory_limiter" {
      check_interval = "1s"
      limit_percentage = 80
      spike_limit_percentage = 20      
      output {
        traces  = [otelcol.processor.transform.default.input,
                   otelcol.connector.host_info.default.input]

      }
    } 


    // Host Info Connector
    otelcol.connector.host_info "default" {
      host_identifiers = [ "k8s.node.name" , "host.name"]
      output {
        metrics = [otelcol.processor.batch.processorbatch.input]
      }
    }

    otelcol.processor.filter "filter_app_metrics" {
      error_mode = "ignore"
      metrics {
          metric = [
            "not IsMatch(resource.attributes[\"k8s.namespace.name\"], \"^xp-acl-.*\")",
          ]
      }
      output {
          metrics = [otelcol.processor.transform.default.input] 
      }
    }  
    // Transform Processor
    otelcol.processor.transform "default" {
      error_mode = "ignore"
      log_statements {
        context = "resource"
        statements = [
          "set(attributes[\"pod\"], attributes[\"k8s.pod.name\"])",
          "set(attributes[\"namespace\"], attributes[\"k8s.namespace.name\"])",
          "set(attributes[\"loki.resource.labels\"], \"cluster, namespace, job, pod\")",
        ]
      }
      //metric_statements {
      //  context = "resource"
      //  statements = [
      //    "set(attributes[\"service.name\"], attributes[\"k8s.pod.labels.app_kubernetes_io/name\"]) where attributes[\"k8s.pod.labels.app_kubernetes_io/name\"] != nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.deployment.name\"]) where attributes[\"k8s.deployment.name\"] != nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.statefulset.name\"]) where attributes[\"k8s.statefulset.name\"] != nil and attributes[\"service.name\"] == nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.daemonset.name\"]) where attributes[\"k8s.daemonset.name\"] != nil and attributes[\"service.name\"] == nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.cronjob.name\"]) where attributes[\"k8s.cronjob.name\"] != nil and attributes[\"service.name\"] == nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.job.name\"]) where attributes[\"k8s.job.name\"] != nil and attributes[\"service.name\"] == nil",
      //    "set(attributes[\"service.name\"], attributes[\"k8s.replicaset.name\"]) where attributes[\"k8s.replicaset.name\"] != nil and attributes[\"service.name\"] == nil",
      //    `replace_pattern(attributes["service.name"], "(-[0-9a-f]{8,10}|-[0-9]+)$", "") where attributes["service.name"] != nil`,
      //    "set(attributes[\"service.namespace\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
      //    "set(attributes[\"job\"], Concat([attributes[\"service.namespace\"], attributes[\"service.name\"]], \"-\")) where attributes[\"service.name\"] != nil and attributes[\"service.namespace\"] != nil",
      //    "set(attributes[\"namespace\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
      //    "set(attributes[\"service.instance.id\"], attributes[\"k8s.pod.uid\"]) where attributes[\"k8s.pod.uid\"] != nil and attributes[\"service.instance.id\"] == nil",
      //  ]
      //}      
      output {
        metrics = [otelcol.processor.batch.processorbatch.input]
        traces = [otelcol.processor.filter.default.input]
      }
    }

    otelcol.processor.filter "default" {
      error_mode = "ignore"
      traces {
        span = [
          "IsMatch(attributes[\"http.route\"], \".*prometheus.*\")",
          //"IsMatch(attributes[\"http.route\"], \".*health.*\")",
          //"IsMatch(attributes[\"http.target\"], \".*health.*\")",
          //"IsMatch(attributes[\"http.target\"], \".*health_check.*\")",
          //"IsMatch(attributes[\"db.operation\"], \".*PING.*\")",
          "IsMatch(attributes[\"express.type\"], \".*middleware.*\")",
          "IsMatch(attributes[\"express.type\"], \".*router.*\")",
          //"IsMatch(attributes[\"db.operation\"], \".*EXIST.*\")",
          //"IsMatch(attributes[\"express.name\"], \".*request handler.*\")",
          //"IsMatch(attributes[\"net.peer.port\"], \".*9000.*\")",
          "IsMatch(attributes[\"db.system\"], \".*redis.*\")",
        ]
      }

      output {
        traces  = [otelcol.processor.transform.rogmen_traces.input]
      }
    }

    otelcol.processor.transform "rogmen_traces" {
      error_mode = "ignore"
      trace_statements {
        context = "resource"
        statements = [
          "set(attributes[\"cluster\"], \"autopilot-cluster-app\")",
          "set(attributes[\"k8s.cluster.name\"], \"autopilot-cluster-app\")" ,
          "set(attributes[\"service.namespace\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
          "set(attributes[\"service.instance.id\"], attributes[\"k8s.pod.uid\"]) where attributes[\"k8s.pod.uid\"] != nil",
          "delete_key(attributes, \"process.command\")",
          "delete_key(attributes, \"process.command_args\")",
          "delete_key(attributes, \"process.executable.path\")",
          "delete_key(attributes, \"process.executable.name\")",
          //"set(attributes[\"service.name\"], attributes[\"k8s.pod.labels.app_kubernetes_io/name\"]) where attributes[\"k8s.pod.labels.app_kubernetes_io/name\"] != nil",
          //"set(attributes[\"service.name\"], attributes[\"k8s.deployment.name\"]) where attributes[\"k8s.deployment.name\"] != nil and attributes[\"service.name\"] == nil",
          //"set(attributes[\"service.name\"], attributes[\"k8s.replicaset.name\"]) where attributes[\"k8s.replicaset.name\"] != nil and attributes[\"service.name\"] == nil",
          //"set(attributes[\"service.name\"], attributes[\"k8s.statefulset.name\"]) where attributes[\"k8s.statefulset.name\"] != nil and attributes[\"service.name\"] == nil",
          //`replace_pattern(attributes["service.name"], "(-[0-9a-f]{8,10}|-[0-9]+)$", "") where attributes["service.name"] != nil`,                    
        ]
      }
      trace_statements {
        context = "span"
        statements = [
          //`set(attributes["http.request.header.x-latam-action-name"], attributes["http.request.header.x-latam-action-name"][0]) where attributes["http.request.header.x-latam-action-name"] != nil`,
          //`set(attributes["http.request.header.x-latam-app-session-id"], attributes["http.request.header.x-latam-app-session-id"][0]) where attributes["http.request.header.x-latam-app-session-id"] != nil`,
          //`set(attributes["http.request.header.x-latam-application-country"], attributes["http.request.header.x-latam-application-country"][0]) where attributes["http.request.header.x-latam-application-country"] != nil`,
          //`set(attributes["http.request.header.x-latam-application-lang"], attributes["http.request.header.x-latam-application-lang"][0]) where attributes["http.request.header.x-latam-application-lang"] != nil`,
          //`set(attributes["http.request.header.x-latam-application-name"], attributes["http.request.header.x-latam-application-name"][0]) where attributes["http.request.header.x-latam-application-name"] != nil`,
          //`set(attributes["http.request.header.x-latam-application-oc"], attributes["http.request.header.x-latam-application-oc"][0]) where attributes["http.request.header.x-latam-application-oc"] != nil`,
          //`set(attributes["http.request.header.x-latam-client-name"], attributes["http.request.header.x-latam-client-name"][0]) where attributes["http.request.header.x-latam-client-name"] != nil`,
          //`set(attributes["http.request.header.x-latam-country"], attributes["http.request.header.x-latam-country"][0]) where attributes["http.request.header.x-latam-country"] != nil`,
          //`set(attributes["http.request.header.x-latam-lang"], attributes["http.request.header.x-latam-lang"][0]) where attributes["http.request.header.x-latam-lang"] != nil`,
          //`set(attributes["http.request.header.x-latam-request-id"], attributes["http.request.header.x-latam-request-id"][0]) where attributes["http.request.header.x-latam-request-id"] != nil`,
          //`set(attributes["http.request.header.x-latam-track-id"], attributes["http.request.header.x-latam-track-id"][0]) where attributes["http.request.header.x-latam-track-id"] != nil`,
          //`set(attributes["http.response.header.x-latam-action-name"], attributes["http.response.header.x-latam-action-name"][0]) where attributes["http.response.header.x-latam-action-name"] != nil`,
          //`set(attributes["http.response.header.x-latam-app-session-id"], attributes["http.response.header.x-latam-app-session-id"][0]) where attributes["http.response.header.x-latam-app-session-id"] != nil`,
          //`set(attributes["http.response.header.x-latam-application-name"], attributes["http.response.header.x-latam-application-name"][0]) where attributes["http.response.header.x-latam-application-name"] != nil`,
          //`set(attributes["http.response.header.x-latam-track-id"], attributes["http.response.header.x-latam-track-id"][0]) where attributes["http.response.header.x-latam-track-id"] != nil`,
          //`set(attributes["http.response.header.x-latam-request-id"], attributes["http.response.header.x-latam-request-id"][0]) where attributes["http.response.header.x-latam-request-id"] != nil`,
          //`set(attributes["http.response.header.x-latam-client-name"], attributes["http.response.header.x-latam-client-name"][0]) where attributes["http.response.header.x-latam-client-name"] != nil`,
          //`set(attributes["service.name"], attributes["k8s.replicaset.name"]) where attributes["service.name"] == nil and attributes["k8s.replicaset.name"] != nil`,
          //"set(attributes[\"service.instance.id\"], attributes[\"k8s.pod.uid\"]) where attributes[\"k8s.pod.uid\"] != nil and attributes[\"service.instance.id\"] == nil",
          //`replace_pattern(name, "^(POST|GET|PUT|DELETE|PATCH) /ws/api", "$1 /*/api")`,
          //`replace_pattern(name, "/v[0-9]+/", "/v*/")`,
          //`replace_pattern(name, "/api/ndc/shopping/", "/api/*/shopping/")`,
          `delete_key(attributes, "http.scheme")`,
          `delete_key(attributes, "http.host")`,
        ]
      }    
      output {
        //traces = [ otelcol.connector.servicegraph.servicegraphbase.input,otelcol.connector.spanmetrics.spanmetricsbse.input,otelcol.processor.tail_sampling.tail_sampling_production.input]
        traces = [ otelcol.processor.batch.processorbatch.input]      
      }
    }

    otelcol.processor.tail_sampling "tail_sampling_production" {
      decision_wait               = "10s"
      num_traces                  = 50000
      expected_new_traces_per_sec = 5000
      policy {
        name = "all_traces_above_1000ms"
        type = "latency"
        latency {
          threshold_ms = 1000
        }
      }
      policy {
        name = "sampling_percentage_probabilistic"
        type = "probabilistic"
        probabilistic {
            sampling_percentage = 50
        }
      }
      policy {
        name = "policy_status_code"
        type = "status_code"
        status_code {
          status_codes = ["ERROR", "UNSET"]
        }
      }
      output {
        traces = [ otelcol.processor.batch.processorbatch.input]
      }
    }

    otelcol.connector.servicegraph "servicegraphbase" {
      dimensions = ["http.method", 
                   "http.target", 
                   "http.status_code", 
                   "http.route",
                   "http.request.header.x.request.id",
                   "http.request.header.x_request_id",
                   "x_request_id",
                   "x-request-id"]
      latency_histogram_buckets = ["100ms", "250ms", "500ms","750ms", "1s", "2s", "5s", "10s", "20s", "60s"]	
      cache_loop = "30s"
      store_expiration_loop = "10s"
      metrics_flush_interval = "60s"      
      store {
      max_items = 20
      ttl = "2s" 
      }
      output {
        metrics = [otelcol.processor.transform.addattrtransform.input]
      }
    }
    otelcol.connector.spanmetrics "spanmetricsbse" {
      dimension {        name = "http.status_code" }
      dimension {        name = "http.route" }      
      dimension {        name = "http.method" }
      dimension {        name = "http.request.header.x.request.id"      }  
      dimension {        name = "http.request.header.x-request-id"      }  
      dimension {        name = "http.request.header.x_request_id"      }  
      dimension {        name = "x-request-id"      }  
      dimension {        name = "x_request_id"      }  
      dimension {        name = "url.path"      }
      dimension {        name = "http.route"      }
      dimension {        name = "http.request.method"       }  
      //aggregation_cardinality_limit = 1000
      aggregation_temporality = "CUMULATIVE"  
      histogram {
        unit = "s"
        explicit {
          buckets = ["100ms", "250ms", "500ms","750ms", "1s", "2s", "5s", "10s", "20s", "60s"]	
        }
      }
      metrics_flush_interval = "15s"
      exemplars {
        enabled = true
        max_per_data_point = 10
      }
      metric_timestamp_cache_size = 1000
      resource_metrics_key_attributes = ["service.namespace", "k8s.cluster.name", "k8s.namespace.name", "service.instance.id"]
      output {
        metrics = [otelcol.processor.batch.processorbatch.input]
      }
    }

    otelcol.processor.transform "addattrtransform" {
      error_mode = "ignore"

      metric_statements {
        context = "datapoint"
        statements = [
          `merge_maps(attributes, resource.attributes, "insert")`,
        ]
      }
      metric_statements {
        context = "resource"
        statements = [
          `replace_pattern(resource.attributes["server_http_request_header_x_request_id"], "[(.*?)]", "")`,
          `set(resource.attributes["x_request_id"], resource.attributes["server_http_request_header_x_request_id"])`,
        ]
      }      
      output {
        metrics = [otelcol.processor.batch.processorbatch.input]
      }
    }
    otelcol.processor.batch "processorbatch" {
      timeout = "10s"
      send_batch_size = 10000
      send_batch_max_size = 11000
      output {
        metrics = [otelcol.exporter.otlphttp.baseotlphttp.input]
        traces  = [otelcol.exporter.otlphttp.baseotlphttp.input]
      }
    }


    prometheus.exporter.self "self_metrics" {}
    prometheus.scrape "scrape_self" {
      targets    = prometheus.exporter.self.self_metrics.targets
      forward_to = [otelcol.receiver.prometheus.prom_to_otlp.receiver]
    }
    otelcol.receiver.prometheus "prom_to_otlp" {
      output {
        metrics = [otelcol.processor.batch.processorbatch.input]
      }
    }
    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.metrics_hello_observability.receiver]
    }

    otelcol.exporter.otlphttp "baseotlphttp" {
      client {
        endpoint ="https://otlp-gateway-prod-us-central-0.grafana.net/otlp"
        auth = otelcol.auth.basic.otlphttp.handler
      }
    }
    otelcol.exporter.otlp "basetotlp" {
      client {
        endpoint = "https://tempo-us-central1.grafana.net:443"
        auth     = otelcol.auth.basic.tempo.handler
        tls {
          insecure = false
          insecure_skip_verify = false
        }
      }
      
    }

    
    // Prometheus configs
    prometheus.remote_write "metrics_hello_observability" {
      external_labels = {
        monitor = "hello-observability",
        cluster = "autopilot-cluster-app",
      }
      endpoint {
        name = "hello-observability-6397c4"
      url  = "https://prometheus-us-central1.grafana.net/api/prom/push"
      basic_auth {
        username = "821057"
        password = "eyJrIjoiNGRjNDU3MmQ1MTVlOTk2ODQ1Zjk1MGNmZDcwNGQyMmIwOGEwNjA3MyIsIm4iOiJyb2dtZW4tcHVibGlzaGVyIiwiaWQiOjgxNDMyMn0="
      }
      }
    }



    
