version: "3"
services:

  # The hello-observability application
  hello-observability.applications.svc.cluster.local:
    image: rmendoza/hello-observability-manual
    volumes:
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-col:4317
      OTEL_SERVICE_NAME: hello-observability
      OTEL_TRACES_EXPORTER: otlp
      HOSTNAME: hello-observability.applications.svc.cluster.local
    ports:
      - "8080:8080"


  ms-service-app-ms1.applications.svc.cluster.local:
    image: rmendoza/ms-service-app-ms1-manual
    volumes:
      # Log files. They are all also accessible to the agent container,
      # through docker volume mount
      - ./logs/ms-service-app-ms1.log:/tmp/ms-service-app-ms1.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      # Tracing configuration
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar    
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-col:4317
      OTEL_SERVICE_NAME: ms-service-app-ms1
      OTEL_TRACES_EXPORTER: otlp
      HOSTNAME: ms-service-app-ms1.applications.svc.cluster.local
    ports:
      - "8081:8081"

  ms-service-app-ms2.applications.svc.cluster.local:
    image: rmendoza/ms-service-app-ms2-manual
    volumes:
      # Log files. They are all also accessible to the agent container,
      # through docker volume mount
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms2.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      # Tracing configuration
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar    
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-col:4317
      OTEL_SERVICE_NAME: ms-service-app-ms2
      OTEL_TRACES_EXPORTER: otlp
      HOSTNAME: ms-service-app-ms2.applications.svc.cluster.local
    ports:
      - "8082:8082"


  # Our load generator
  load-generator:
    image: curlimages/curl:latest
    volumes:
      - ../hello-observability/load-generator.sh:/tmp/load-generator.sh
    command: /bin/sh -c "/tmp/load-generator.sh"
  
  agent-operator:
    image: grafana/agent:v0.33.2
    volumes:
      - ./config/agent/agent.yaml:/etc/agent-config/agent.yaml
      # - /:/host/root:ro,rslave
      # - /sys:/host/sys:ro,rslave
      # - /proc:/host/proc:ro,rslave
      - /tmp/agent:/etc/agent
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
#      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent-operator

  agent-loki:
    image: grafana/agent:v0.33.2
    volumes:
      - ./config/logs/agent.yaml:/etc/agent-config/agent.yaml
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms2.log
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms1.log
      - ./logs/access_log.log:/tmp/access_log.log
      # - /:/host/root:ro,rslave
      # - /sys:/host/sys:ro,rslave
      # - /proc:/host/proc:ro,rslave
      - /tmp/agent:/etc/agent
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
#      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent-loki

  otel-col:
    image: otel/opentelemetry-collector-contrib:0.97.0
    container_name: otel-col
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./config/otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
      - ./config/otelcollector/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
    environment:
      HOSTNAME: otel-col


