# Source: k8s-monitoring/charts/alloy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-alloy
  namespace: monitoring
  labels:
    helm.sh/chart: alloy-0.9.1
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: grafana-k8s-monitoring
    
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
---