# Source: k8s-monitoring/charts/alloy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-alloy
  namespace: monitoring
  labels:
    helm.sh/chart: alloy-0.9.1
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: grafana-k8s-monitoring
    
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
---
# Source: k8s-monitoring/charts/beyla/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-beyla
  namespace: monitoring
  labels:
    helm.sh/chart: beyla-1.4.3
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.8.4"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
automountServiceAccountToken: true
---
# Source: k8s-monitoring/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  labels:    
    helm.sh/chart: kube-state-metrics-5.25.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "2.13.0"
    release: grafana-k8s-monitoring
  name: grafana-k8s-monitoring-kube-state-metrics
  namespace: monitoring
---
# Source: k8s-monitoring/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-prometheus-node-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: prometheus-node-exporter-4.39.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.8.2"
    release: grafana-k8s-monitoring
automountServiceAccountToken: false
---