apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-auto-instrumentation
  namespace: opentelemetry-collector
spec:
#  exporter:
#    endpoint: http://lb-grafana-alloy-traces.monitoring.svc.cluster.local:4317
  propagators:
  - tracecontext
  - baggage
  sampler:
    argument: '1'
    type: parentbased_traceidratio

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.18.0
    env:
    - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS
      value: "x-request-id"
    - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_RESPONSE_HEADERS
      value: "x-request-id"
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_RESPONSE_HEADERS
      value: "x-request-id"
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS
      value: "x-request-id"
    - name: OTEL_INSTRUMENTATION_SERVLET_CAPTURE_HEADERS
      value: "x-request-id"
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://lb-grafana-alloy-traces.monitoring.svc.cluster.local:4317" 
    - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      value: "http://grafana-alloy-metrics-apps.monitoring.svc.cluster.local:4317" 
    - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_APACHE_HTTPCLIENT_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_JETTY_HTTPCLIENT_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_JAVA_HTTP_CLIENT_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_EMIT_EXPERIMENTAL_TELEMETRY
      value: "true"
    - name: OTEL_INSTRUMENTATION_HTTP_SERVER_EMIT_EXPERIMENTAL_TELEMETRY
      value: "true"
    - name: OTEL_INSTRUMENTATION_COMMON_METRICS_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_SERVLET_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_HTTP_URL_CONNECTION_ENABLED
      value: "true"
    - name: OTEL_JAVAAGENT_LOGGING
      value: "simple"
    - name: OTEL_INSTRUMENTATION_JDBC_CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES
      value: "true"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_PROPAGATORS
      value: "tracecontext,baggage"            
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: node-auto-instrumentation
  namespace: opentelemetry-collector
spec:
#  exporter:
#    endpoint: http://lb-grafana-alloy-traces.monitoring.svc.cluster.local:4317
  propagators:
  - tracecontext
  - baggage
  sampler:
    argument: '1'
    type: parentbased_traceidratio

  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.60.1
    env:
    - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: "http://lb-grafana-alloy-traces.monitoring.svc.cluster.local:4317" 
    - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
      value: "http://grafana-alloy-metrics-apps.monitoring.svc.cluster.local:4317" 
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_PROPAGATORS
      value: "tracecontext,baggage"      