apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: auto-instrumentation
  namespace: opentelemetry-collector
spec:
  sampler:
    argument: '1'
    type: parentbased_traceidratio
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.30.0
    env:
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS
      value: "true"

  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.40.0
    env:
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS
      value: "true"
---
 apiVersion: opentelemetry.io/v1beta1
 kind: OpenTelemetryCollector
 metadata:
   labels:
     app: opentelemetry
     component: collector
   name: otel-collector
   namespace: opentelemetry-collector
 spec:
   mode: sidecar
   config: 
     receivers:
       otlp:
         protocols:
           grpc:
             endpoint: 0.0.0.0:4317
     exporters:
       debug:
        verbosity: basic
        sampling_initial: 5
        sampling_thereafter: 200       
       otlp:
         endpoint: http://lb-grafana-alloy-traces.monitoring.svc.cluster.local:4317
         tls:
           insecure: true
     processors:
       batch:
         timeout: 200ms
         send_batch_size: 512
         send_batch_max_size: 11000
     service:
       pipelines:
         traces:
           receivers: [otlp]
           processors: [batch]
           exporters: [otlp]             

