version: "3.4"
services:

  # The hello-observability application
  hello-observability.applications.svc.cluster.local:
    image: rmendoza/hello-observability-manual:v2
    volumes:
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar -Dotel.instrumentation.micrometer.enabled=true -Dotel.instrumentation.common-metrics.enabled=true -Dotel.instrumentation.common.default-enabled=true -Dotel.instrumentation.servlet-metrics.enabled=true -Dotel.instrumentation.common.enabled=true -Dotel.instrumentation.runtime-telemetry.enabled=true
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:  http://grafana-alloy-traces:4317
      OTEL_SERVICE_NAME: hello-observability
      OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS: true
      OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS: true
      OTEL_INSTRUMENTATION_COMMON_METRICS_ENABLED: true
      OTEL_INSTRUMENTATION_SERVLET_METRICS_ENABLED: true
      OTEL_INSTRUMENTATION_JDBC_CAPTURE_EXPERIMENTAL_SPAN_ATTRIBUTES: true
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_PORT: 9464
      OTEL_PROPAGATORS: "tracecontext,baggage"
      HOSTNAME: hello-observability.applications.svc.cluster.local
    ports:
      - "8080:8080"


  ms-service-app-ms1.applications.svc.cluster.local:
    image: rmendoza/ms-service-app-ms1-manual:v2
    volumes:
      # Log files. They are all also accessible to the agent container,
      # through docker volume mount
      - ./logs/ms-service-app-ms1.log:/tmp/ms-service-app-ms1.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      # Tracing configuration
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar    
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_SERVICE_NAME: ms-service-app-ms1
      OTEL_TRACES_EXPORTER: otlp
      OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS: true
      OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS: true
      OTEL_METRICS_EXPORTER: otlp
      OTEL_PROPAGATORS: "tracecontext,baggage"
      HOSTNAME: ms-service-app-ms1.applications.svc.cluster.local
    ports:
      - "8081:8081"

  ms-service-app-ms2.applications.svc.cluster.local:
    image: rmendoza/ms-service-app-ms2-manual:v2
    volumes:
      # Log files. They are all also accessible to the agent container,
      # through docker volume mount
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms2.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      # Tracing configuration
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar    
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-alloy-traces:4317
      OTEL_SERVICE_NAME: ms-service-app-ms2
      OTEL_TRACES_EXPORTER: otlp
      OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS: true
      OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS: true
      OTEL_METRICS_EXPORTER: otlp
      OTEL_PROPAGATORS: "tracecontext,baggage"
      HOSTNAME: ms-service-app-ms2.applications.svc.cluster.local
    ports:
      - "8082:8082"

  grafana-alloy-traces:
    image: grafana/alloy:v1.8.0
    volumes:
      - ./config/config-traces.alloy:/etc/agent/config.alloy
    command:
      - run
      - /etc/agent/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
 #     - -config.file=/etc/agent/config.river
 #     - -config.file=/etc/agent-config/agent.yaml      
    environment:
      HOSTNAME: grafana-alloy-traces
    ports:
       - "4317:4317"
       - "4318:4318"
       - "9464:9464"
       
  grafana-alloy-metrics-logs:
    image: grafana/alloy:v1.8.0
    volumes:
      - ./config/config-metrics-logs.alloy:/etc/agent/config.alloy
      - ./logs/hello-observability.log:/tmp/hello-observability.log
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms2.log
      - ./logs/ms-service-app-ms2.log:/tmp/ms-service-app-ms1.log      
    command:
      - run
      - /etc/agent/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
 #     - -config.file=/etc/agent/config.river
 #     - -config.file=/etc/agent-config/agent.yaml      
    environment:
      HOSTNAME: grafana-alloy-metrics
   
  # Our load generator
  ubuntu-local:
    image: ubuntu
    restart: on-failure
    command: ["sleep","infinity"]


