# Source: k8s-monitoring/templates/tests/test.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "test-grafana-k8s-monitoring"
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "grafana-k8s-monitoring"
    app.kubernetes.io/version: 2.8.3
    helm.sh/chart: "k8s-monitoring-1.6.0"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
data:
  testQueries.json: |-
    {
      "queries": [
        {
          "query": "up{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "alloy_build_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "kubernetes_build_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "node_cpu_usage_seconds_total{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "machine_memory_bytes{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "kube_node_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "node_exporter_build_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "opencost_build_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        },
        {
          "query": "grafana_kubernetes_monitoring_build_info{cluster=\"autopilot-cluster-app\"}",
          "type": "promql"
        }
      ]
    }
