
# Source: k8s-monitoring/charts/alloy-events/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-k8s-monitoring-alloy-events
  labels:
    helm.sh/chart: alloy-events-0.9.1
    app.kubernetes.io/name: alloy-events
    app.kubernetes.io/instance: grafana-k8s-monitoring
    
    app.kubernetes.io/version: "v1.4.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: networking
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy-events
    app.kubernetes.io/instance: grafana-k8s-monitoring
  internalTrafficPolicy: Cluster
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: "TCP"
---