# Source: k8s-monitoring/charts/opencost/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-k8s-monitoring-opencost
  namespace: monitoring
  labels:
    helm.sh/chart: opencost-1.42.0
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.111.0"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: grafana-k8s-monitoring
  type: "ClusterIP"
  ports:
    - name: http
      port: 9003
      targetPort: 9003
---