apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ms-hello-observability-services
  namespace: "applications"  
  labels:
    app: ms-hello-observability-services
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-hello-observability-services
  template:
    metadata:
      labels:
        app: ms-hello-observability-services
#      annotations:
#        instrumentation.opentelemetry.io/inject-java: "opentelemetry-collector/auto-instrumentation"
#        instrumentation.opentelemetry.io/container-names: "app"             
    spec:
      containers:
        - name: app
          image: rmendoza/hello-observability-simple
          imagePullPolicy: Always
          ports:
          - name: out-http
            containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 50
            periodSeconds: 5
            initialDelaySeconds: 40
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ms-service-app-ms2
  namespace: "applications"  
  labels:
    app: ms-service-app-ms2
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-service-app-ms2
  template:
    metadata:
      labels:
        app: ms-service-app-ms2
#      annotations:
#        instrumentation.opentelemetry.io/inject-java: "opentelemetry-collector/auto-instrumentation"
#        instrumentation.opentelemetry.io/container-names: "app"             
    spec:
      containers:
        - name: app
          image: rmendoza/ms-service-app-ms2-simple
          imagePullPolicy: Always
          ports:
          - name: out-http
            containerPort: 8082
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            failureThreshold: 50
            periodSeconds: 5
            initialDelaySeconds: 40
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8082
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8082
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ms-service-app-ms1
  namespace: "applications"  
  labels:
    app: ms-service-app-ms1
    tier: backend    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-service-app-ms1
  template:
    metadata:
      labels:
        app: ms-service-app-ms1
#      annotations:
#        instrumentation.opentelemetry.io/inject-java: "opentelemetry-collector/auto-instrumentation"
#        instrumentation.opentelemetry.io/container-names: "app"             

    spec:
      containers:
        - name: app
          image: rmendoza/ms-service-app-ms1-simple
          imagePullPolicy: Always
          ports:
          - name: out-http
            containerPort: 8081
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 50
            periodSeconds: 5
            initialDelaySeconds: 40
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ms-hello-observability-services"
  namespace: "applications"
  labels:
    app: "ms-hello-observability-services"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "ms-hello-observability-services"
  type: "ClusterIP"         
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "lb-ms-hello-observability-services"
  namespace: "applications"
  labels:
    app: "ms-hello-observability-services"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "ms-hello-observability-services"
  type: "LoadBalancer"
  loadBalancerIP: ""
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ms-service-app-ms2"
  namespace: "applications"
  labels:
    app: "ms-service-app-ms2"
spec:
  ports:
  - protocol: "TCP"
    port: 8082
    targetPort: 8082
  selector:
    app: "ms-service-app-ms2"
  type: "ClusterIP"     
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "ms-service-app-ms1"
  namespace: "applications"
  labels:
    app: "ms-service-app-ms1"
spec:
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  selector:
    app: "ms-service-app-ms1"
  type: "ClusterIP"    